"""
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
"""

x: int = 1
y: int = 2
z: int = 0
s: int = 2  # 2 is first even valued term, pre-include it

while z < 4000000:
    
    z = x + y    # first iteration will be 3
    if z % 2 == 0:
        s += z
    x = y
    y = z
    
print(s)
    