# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# OLD
list1 = [1, 2]
while True:
    z = sum(list1[-2:])
    if z < 4000000:
        list1.append(z)
    else:
        break

print(f"SUM: {sum([x for x in list1 if x % 2 == 0])}")

# NEW
a, b, s = 1, 2, 2
while True:
    z = a + b
    if z < 4000000:
        a, b = b, z
        if z % 2 == 0:
            s += z
    else:
        break

print(f"SUM: {s}")

# GPT Golfed version
a, b, s = 1, 2, 0
while b <= 4000000:
    if b % 2 == 0:
        s += b
    a, b = b, a + b
print(s)

